<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 2" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="C:\omaTimer\OmaTimer\Test\__init__.py" status="error" test="__init__" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\Anja\.p2\pool\plugins\org.python.pydev.core_6.3.2.201803171248\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:\Users\Anja\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\requests\__init__.py", line 46, in <module>
    from .exceptions import RequestsDependencyWarning
ImportError: attempted relative import with no known parent package
ERROR: Module: __init__ could not be imported (file: C:\omaTimer\OmaTimer\Test\__init__.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="OmaTimer __init__.py (1)"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
